export const ADD_PROBABILITY = "ADD_PROBABILITY";
export const SELECT_PROBABILITY_BY_CURRENT_KEY =
  "SELECT_PROBABILITY_BY_CURRENT_KEY";
export const EDIT_KEY_CURRENT_PROBA = "EDIT_KEY_CURRENT_PROBA";
export const EDIT_KEY_SELECTED_HISTORY_PROBA =
  "EDIT_KEY_SELECTED_HISTORY_PROBA";
// export const GET_LAST_PROBABILITY = "GET_LAST_PROBABILITY";
